import { v5 as uuidv5 } from 'uuid';
import { IStringKeyedObject, IViewModel, IInstanceWrapper, IRIVM } from "./interfaces";
import type { StaticGraph, StaticNode, StaticResourceDescriptors, IStaticDescriptorConfig } from "./static-types";

// TODO: make this customizable.
const DEFAULT_LANGUAGE = "en";
const SLUG_LENGTH = 20;
const UUID_NAMESPACE = '1a79f1c8-9505-4bea-a18e-28a053f725ca'; // Generated for this purpose.
const UUID_NAMESPACE_COMPRESSION = uuidv5('compression', '1a79f1c8-9505-4bea-a18e-28a053f725ca');

let currentLanguage: string | undefined;

function getCurrentLanguage(): string {
  return currentLanguage || ((typeof navigator != 'undefined' && navigator.language) || DEFAULT_LANGUAGE).slice(0, 2);
}

function setCurrentLanguage(lang: string) {
  currentLanguage = lang;
}

/**
 * Slugify a string safely for use in file paths
 * Removes/replaces dangerous characters and limits length
 */
function slugify(name: string, maxLength: number = 100, useUnderscoreForHyphen: boolean = false): string {
  if (!name || typeof name !== 'string') {
    name = `${name}`;
  }

  // Remove or replace dangerous characters
  let slug = name
    .toLowerCase()
    .trim()
    // Replace spaces and underscores with hyphens
    .replace(/[\s_]+/g, '-')
    // Remove any character that isn't alphanumeric or hyphen
    .replace(/[^a-z0-9-]/g, '')
    // Remove consecutive hyphens
    .replace(/-+/g, '-')
    // Remove leading/trailing hyphens
    .replace(/^-|-$/g, '')
    // Limit length
    .slice(0, maxLength);
  if (useUnderscoreForHyphen) {
    slug = slug.replace('-', '_');
  }

  if (name && !slug) {
    throw new Error(`Slugification resulted in empty string for input: ${name}`);
  }

  slug = slug.substr(0, SLUG_LENGTH);
  return slug;
}

class AttrPromise<T> extends Promise<T> implements IStringKeyedObject {
  [key: string | symbol]: any;
  [Symbol.toPrimitive]: undefined;
  constructor(
    executor: (
      resolve: (value: T | PromiseLike<T>) => void,
      reject: (reason: any) => void,
    ) => void,
  ) {
    super(executor);
    const proxy = new Proxy(this, {
      set: (object: AttrPromise<T>, keyObj, value) => {
        if (keyObj.toString() == 'id') {
          object.id = value;
        }
        object.then((val: any) => {
          val[keyObj] = value;
          return val;
        });
        return true;
      },
      get: (object: AttrPromise<T>, keyObj: string | symbol) => {
        if (keyObj == 'then') {
          return object.then.bind(this);
        }
        if (keyObj == 'id') {
          return object.id;
        }
        if (keyObj in object) {
          const value: any = object[keyObj];
          if (typeof value === "function") {
            return value.bind(object);
          }
          return value;
        }
        const key = keyObj.toString();
        if (key in object) {
          const value: any = object[key];
          if (typeof value === "function") {
            return value.bind(object);
          }
          return value;
        }
        if (object instanceof Promise) {
          return object.then((val: any) => {
            return val ? val[keyObj] : val;
          });
        }
        return object[keyObj];
      },
    });
    return proxy;
  }
}

const KEY_COMPRESSION_LENGTH = 1000;
function generateUuidv5(group: [type: string, id?: string], key: string | string[]) {
  if (Array.isArray(key)) {
    let shortKey = '';
    let keyTracker = '';
    key.forEach(k => {
      if (keyTracker.length + k.length + 1 > KEY_COMPRESSION_LENGTH) {
        shortKey = uuidv5(shortKey + '>' + keyTracker, UUID_NAMESPACE_COMPRESSION);
        keyTracker = k;
      } else {
        keyTracker += ';' + k;
      }
    });
  }
  return uuidv5(`${group[0]}:${group[1]}:${key}`, UUID_NAMESPACE);
}

const DESCRIPTOR_FUNCTION_ID = "60000000-0000-0000-0000-000000000001";

/**
 * Builds resource descriptors using string templates and node values.
 *
 * Descriptors are metadata fields (like "name", "description", "map_popup") that are
 * dynamically generated by substituting node values into string templates.
 *
 * Template format: "The <Node Name> in <Another Node>" where placeholders like
 * <Node Name> are replaced with actual values from the resource's tiles.
 *
 * @param graph - The graph definition containing descriptor configuration
 * @param nodes - Map of node IDs to node objects for value lookup
 * @param wrapper - IInstanceWrapper for retrieving pseudo values from Rust
 * @returns Promise resolving to StaticResourceDescriptors with populated fields
 *
 * @example
 * // Given a descriptor config with template: "The <Title> from <Year>"
 * // And a resource with Title="Rome" and Year="100 AD"
 * // Returns descriptors with populated field: "The Rome from 100 AD"
 */
async function buildResourceDescriptors(
  graph: StaticGraph,
  nodes: Map<string, StaticNode>,
  wrapper: IInstanceWrapper<any>
): Promise<StaticResourceDescriptors> {
  // Import StaticResourceDescriptors here to avoid circular dependency
  const { StaticResourceDescriptors } = await import("./static-types");

  const descriptors = StaticResourceDescriptors.empty();
  let descriptorConfig: IStaticDescriptorConfig | undefined = undefined;

  // Find descriptor configuration in graph functions
  if (graph.functions_x_graphs) {
    const descriptorNode = graph.functions_x_graphs.find(
      node => node.function_id === DESCRIPTOR_FUNCTION_ID
    );
    if (descriptorNode) {
      descriptorConfig = descriptorNode.config;
    }
  }

  if (!descriptorConfig) {
    return descriptors;
  }

  // Process each descriptor type (name, description, map_popup, etc.)
  for (const [descriptor, config] of Object.entries(descriptorConfig.descriptor_types)) {
    const semanticNode = nodes.get(config.nodegroup_id);
    let description = config.string_template;

    if (!description) {
      continue;
    }

    // Extract placeholder names from template (e.g., <Node Name>)
    let requestedNodes = description.match(/<[A-Za-z _-]*>/g) || [];

    // Find nodes matching the placeholders
    const relevantNodes = [...nodes.values()]
      .filter(node =>
        node.nodegroup_id === config.nodegroup_id &&
        [...requestedNodes].includes(`<${node.name}>`)
      )
      .map(node => [node.name, node.alias || '']);

    let relevantValues: [string, string | undefined][] = [];

    // First try to find all values on one tile for consistency
    if (semanticNode) {
      const retrieved = await wrapper.retrievePseudo(semanticNode.alias || '');
      let semanticValue = retrieved ? await retrieved[0] : null;

      // Handle PseudoList (which is an array)
      if (Array.isArray(semanticValue)) {
        semanticValue = await semanticValue[0];
        // Extract value from the list element if it has getValue
        if (semanticValue && typeof semanticValue.getValue === 'function') {
          semanticValue = await semanticValue.getValue();
        }
      } else if (semanticValue && semanticValue.inner) {
        // Handle nested value (e.g., StringViewModel)
        relevantValues.push([semanticNode.name || '', await semanticValue.getValue()]);
        semanticValue = await semanticValue.inner.getValue();
      } else {
        semanticValue = await semanticValue.getValue();
      }

      // Collect values from semantic node
      if (semanticValue) {
        relevantValues = [
          ...relevantValues,
          ...await Promise.all(
            relevantNodes
              .filter(([_, alias]) => semanticValue.__has(alias))
              .map(([name, alias]) =>
                semanticValue[alias].then((value: IViewModel) => [name, value])
              )
          )
        ];
      }
    }

    // Replace placeholders with values
    if (relevantValues) {
      description = relevantValues.reduce(
        (desc, [name, value]) =>
          value ? desc.replace(`<${name}>`, value) : desc,
        description
      );
    }

    // Check if there are still unreplaced placeholders
    requestedNodes = description.match(/<[A-Za-z _-]*>/g) || [];

    // If so, try retrieving values individually
    if (requestedNodes.length) {
      relevantValues = await Promise.all(
        relevantNodes.map(async ([name, alias]) => {
          const values = await wrapper.retrievePseudo(alias);
          if (!values || values.length === 0) {
            return [name, undefined] as [string, string | undefined];
          }
          // Extract the actual string value from the view model
          const viewModel = values[0];
          const value = viewModel && typeof viewModel.getValue === 'function'
            ? await viewModel.getValue()
            : viewModel;
          return [name, typeof value === 'string' ? value : undefined] as [string, string | undefined];
        })
      );

      if (relevantValues) {
        description = relevantValues.reduce(
          (desc, [name, value]) =>
            value ? desc.replace(`<${name}>`, value) : desc,
          description
        );
      }
    }

    // Assign to descriptor
    descriptors[descriptor] = description;
  }

  return descriptors;
}

/**
 * Serialize a Map<string, any> to a simple object for passing to WASM
 * Converts values to Option<bool>: Some(true)=truthy, Some(false)=false, None=undefined
 * This avoids expensive JsValue iteration and type checking in Rust
 */
function serializeValuesMap(map: Map<string, any>): Record<string, boolean | null> {
  const result: Record<string, boolean | null> = {};
  for (const [key, value] of map.entries()) {
    if (value === undefined) {
      result[key] = null;  // None in Rust
    } else if (value === false) {
      result[key] = false;  // Some(false) in Rust
    } else {
      result[key] = true;  // Some(true) in Rust (any truthy value)
    }
  }
  return result;
}

export { slugify, AttrPromise, getCurrentLanguage, generateUuidv5, setCurrentLanguage, buildResourceDescriptors, DESCRIPTOR_FUNCTION_ID, serializeValuesMap };
