[package]
name = "alizarin-clm-napi"
version = "2.0.0-beta.1"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "NAPI binding for the Alizarin CLM (reference) extension"

[lib]
crate-type = ["cdylib"]

[dependencies]
alizarin-clm-core = { path = "../core" }
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
