[package]
name = "alizarin-geo-napi"
version = "2.0.0-beta.6"
edition = "2021"
license = "AGPL-3.0-or-later"
description = "NAPI binding for the Alizarin geo (geojson-feature-collection) extension"

[lib]
crate-type = ["cdylib"]

[dependencies]
alizarin-geo-core = { path = "../core" }
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
