/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The geo handler's `TypeHandlerInfo` pointer, as a `BigInt`. Pass to
 * `registerExtensionHandler` from `@alizarin/napi`.
 */
export declare function geoHandlerPtr(): bigint
/** Set the max coordinate count per feature collection (mirrors the Python knob). */
export declare function setCoordLimit(limit?: number | undefined | null): void
