// Auto-registers the geo (geojson-feature-collection) handler with @alizarin/napi
// on import. The native binding (index.js) is generated by `napi build` and
// exposes `geoHandlerPtr()` — a BigInt pointer to the handler's TypeHandlerInfo,
// which we hand to the host's registerExtensionHandler (the NAPI analogue of
// Python's `import alizarin_geo`).
//
//   const alizarin = require('@alizarin/napi');
//   require('@alizarin/geo'); // registers the handler
//
const binding = require('./index.js')
const { registerExtensionHandler } = require('@alizarin/napi')

registerExtensionHandler(binding.geoHandlerPtr())

module.exports = binding
