/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Build a StaticGraph from model CSVs (graph.csv, nodes.csv, optional collections.csv).
 *
 * Returns the graph as a JSON string. The `rdm_namespace` is used for
 * deterministic ID generation (typically a UUID or URL).
 */
export declare function buildGraphFromCsvs(graphCsv: string, nodesCsv: string, collectionsCsv: string | undefined | null, rdmNamespace: string): any
/**
 * Build StaticResources from a business data CSV, given a graph JSON string
 * and collections JSON string (as returned by `buildGraphFromCsvs`).
 *
 * Returns the resources wrapped in the `{ business_data: { resources: [...] } }`
 * format expected by PrebuildLoader.
 */
export declare function buildBusinessDataFromCsv(csvData: string, graphJson: string, collectionsJson: string): any
/**
 * Coerce a value using the registered extension handler for the given datatype.
 *
 * Returns `{ tileData, displayValue }` or null if no handler is registered.
 */
export declare function extensionCoerce(datatype: string, value: any, config?: any | undefined | null): any | null
/**
 * Render a display string for tile data using the extension handler.
 *
 * Returns the display string, or null if no handler or no display.
 */
export declare function extensionRenderDisplay(datatype: string, tileData: any, language: string): string | null
/**
 * Resolve markers in tile data using the extension handler.
 *
 * Returns the resolved tile data value.
 */
export declare function extensionResolveMarkers(datatype: string, tileData: any, language: string): any
/** Check if an extension handler is registered for the given datatype. */
export declare function hasExtensionHandler(datatype: string): boolean
/** List all registered extension handler datatypes. */
export declare function getRegisteredExtensionHandlers(): Array<string>
/** Parse SKOS RDF/XML and return all collections as a JSON array. */
export declare function parseSkosXml(xmlContent: string, baseUri: string): any
/** Parse SKOS RDF/XML and return a single collection (the first one found). */
export declare function parseSkosXmlToCollection(xmlContent: string, baseUri: string): any
/**
 * Build a mapping from node alias to collection ID based on graph definition.
 *
 * Equivalent to WASM's `buildAliasToCollectionMap`.
 */
export declare function buildAliasToCollectionMap(graphJson: string, resolvableDatatypes?: Array<string> | undefined | null, configKeys?: Array<string> | undefined | null): Record<string, string>
/**
 * Scan a JSON tree to find which collections are needed for resolution.
 *
 * Equivalent to WASM's `findNeededCollections`.
 */
export declare function findNeededCollections(treeJson: string, aliasToCollection: Record<string, string>): Array<string>
/** Check if a string is a valid UUID. */
export declare function isValidUuid(s: string): boolean
/** Get the default resolvable datatypes (concept, concept-list). */
export declare function getDefaultResolvableDatatypes(): Array<string>
/** Get the default config keys for collection IDs. */
export declare function getDefaultConfigKeys(): Array<string>
/**
 * Import a prebuild/pkg directory: register graphs, load SKOS collections,
 * and load ontology configs.
 *
 * 1. Loads and registers all graphs from graphs/resource_models/ and graphs/branches/
 * 2. Parses SKOS XML from reference_data/collections/ into the global RDM cache
 * 3. Loads ontology configs from ontologies/ (if present)
 *
 * Returns `{ graphIds, collectionIds, collections, ontologyConfigs }`.
 */
export declare function importPrebuild(prebuildDir: string, baseUri: string): any
export declare class NapiRdmCache {
  constructor()
  /** Load collections from a SKOS JSON string. */
  loadFromSkosJson(jsonStr: string): void
  /** Load a single collection from JSON. */
  loadCollectionJson(jsonStr: string): void
  get collectionCount(): number
  /** Check if a collection is already in the cache. */
  hasCollection(collectionId: string): boolean
  /** Add a collection from a JSON string of concepts. */
  addCollectionFromJson(collectionId: string, jsonStr: string): void
  /** Get the parent concept ID for a concept within a collection. */
  getParentId(collectionId: string, conceptId: string): string | null
  /** Remove a collection from the cache. */
  removeCollection(collectionId: string): boolean
  /** Clear all collections from the cache. */
  clear(): void
  /** Resolve labels to UUIDs using this cache for lookups. */
  resolveLabels(treeJson: string, aliasToCollection: Record<string, string>, strict: boolean): any
}
export declare class NapiNodeConfigManager {
  constructor()
  /** Build node configs from a graph JSON string. */
  buildFromGraphJson(graphJson: string): void
  /** Build node configs from a NapiStaticGraph. */
  buildFromGraph(graph: NapiStaticGraph): void
}
export declare class NapiTileData {
  has(key: string): boolean
  get(key: string): any
  set(key: string, value: any): void
  delete(key: string): boolean
  keys(): Array<string>
}
export declare class NapiStaticTile {
  constructor(nodegroupId: string, tileid?: string | undefined | null, sortorder?: number | undefined | null, resourceinstanceId?: string | undefined | null, parenttileId?: string | undefined | null)
  get data(): NapiTileData
  /**
   * Setter is a no-op — data is always accessed via the NapiTileData getter.
   * Exists to prevent TypeError in strict mode when JS does
   * `tile.data = tile.data || new Map()`.
   */
  set data(value: any)
  get tileid(): string | null
  set tileid(value?: string | undefined | null)
  get nodegroupId(): string
  get sortorder(): number | null
  get resourceinstanceId(): string
  get parenttileId(): string | null
  set parenttileId(value?: string | undefined | null)
  get provisionaledits(): any
  /** Generate a tile ID if not already set. */
  ensureId(): string
}
export declare class NapiPseudoValue {
  get node(): any
  get nodeId(): string | null
  get nodeAlias(): string | null
  get datatype(): string
  get nodegroupId(): string | null
  get isCollector(): boolean
  get independent(): boolean
  get exportable(): boolean
  get isrequired(): boolean
  get issearchable(): boolean
  get ontologyclass(): any
  get hascustomalias(): boolean
  get parentproperty(): string | null
  get description(): any
  get name(): any
  get tileId(): string | null
  get tileData(): any
  get valueLoaded(): boolean
  hasTileData(): boolean
  setTileData(value: any): void
  get childNodeAliases(): any
  getChildNodeId(index: number): string | null
  isIterable(): boolean
  /** Get sortorder from the tile */
  get sortorder(): any
  /** Snapshot all properties in one call (avoids multiple N-API boundary crossings) */
  toSnapshot(): any
  /** Clear tile data */
  clear(): void
  get tile(): NapiStaticTile | null
  set tile(tile?: NapiStaticTile | undefined | null)
  /** Get the inner PseudoValueCore wrapped as NapiPseudoValue. */
  get inner(): NapiPseudoValue | null
  /** Returns null — value is managed JS-side via _cachedValue. */
  get value(): any
}
export declare class NapiPseudoList {
  get nodeAlias(): string
  get totalValues(): number
  get isLoaded(): boolean
  get isSingle(): boolean
  isIterable(): boolean
  getValue(valueIndex: number): NapiPseudoValue | null
  getAllValues(): Array<NapiPseudoValue>
}
export declare class NapiPopulateResult {
  getValueAliases(): Array<string>
  getValue(alias: string): NapiPseudoList | null
  /** Get all values as a JSON map (single boundary crossing). */
  getAllValues(): any
  get allValuesMap(): any
  get allNodegroupsMap(): any
}
export declare class NapiEnsureNodegroupResult {
  getValueAliases(): Array<string>
  getValue(alias: string): NapiPseudoList | null
  getAllValues(): any
  get impliedNodegroups(): Array<string>
  get allNodegroupsMap(): any
}
export declare class NapiValuesFromNodegroupResult {
  getAllValues(): any
  get impliedNodegroups(): Array<string>
}
export declare class NapiResourceInstanceWrapper {
  /** Create a wrapper for a given graph (must be registered). */
  constructor(graphId: string)
  /** Load tiles from a JSON string (single-pass deserialization). */
  loadTiles(tilesJson: string): void
  /** Load tiles directly from a StaticResource JSON string (single-pass deserialization). */
  loadTilesFromResource(resourceJson: string): void
  /**
   * Load tiles directly from a NapiStaticResourceRegistry by resource ID.
   * This avoids the JS round-trip of serializing tiles to JS and back.
   */
  loadFromRegistry(resourceId: string, registry: NapiStaticResourceRegistry): boolean
  /** Append tiles incrementally (for lazy loading). */
  appendTiles(tilesJs: any): void
  getTileCount(): number
  /**
   * Export all tiles as a JSON string.
   * Returns the wrapper's current tile state (including any mutations from setTileDataForNode).
   * Returned as a string for fast boundary crossing — call JSON.parse() on the JS side.
   */
  exportTilesJson(): string
  /** Prune tiles to only keep those in permitted nodegroups. */
  pruneResourceTiles(): void
  tilesLoaded(): boolean
  getAllTileIds(): Array<string>
  getTileIdsByNodegroup(nodegroupId?: string | undefined | null): Array<string>
  getTile(tileId: string): any
  getTileData(tileId: string, nodeId: string): any
  /**
   * Set a single node's data in a tile, mutating in place.
   * Returns true if the tile was found and updated.
   */
  setTileDataForNode(tileId: string, nodeId: string, value: any): boolean
  hasTilesForNodegroup(nodegroupId: string): boolean
  getNodegroupCount(): number
  setLazy(lazy: boolean): void
  isNodegroupLoaded(nodegroupId?: string | undefined | null): boolean
  isNodegroupLoadedOrLoading(nodegroupId?: string | undefined | null): boolean
  tryAcquireNodegroupLock(nodegroupId: string): boolean
  getMissingNodegroupsForChildren(parentNodeId: string): Array<string>
  getResourceId(): string | null
  getName(): any
  getDescriptors(recompute: boolean): any
  /** Populate the pseudo cache for the given nodegroups. */
  populate(lazy: boolean, nodegroupIds: Array<string>, rootNodeAlias: string): NapiPopulateResult
  /** Ensure a single nodegroup is loaded and return structured values. */
  ensureNodegroup(allValuesJs: any, allNodegroupsJs: any, nodegroupId: string, addIfMissing: boolean, nodegroupPermissionsJs: any, doImpliedNodegroups: boolean): NapiEnsureNodegroupResult
  /** Build pseudo values from tiles for a specific nodegroup. */
  valuesFromResourceNodegroup(existingValuesJs: any, nodegroupTileIds: Array<string>, nodegroupId: string): NapiValuesFromNodegroupResult
  /**
   * Resolve a dot-separated path to its target node metadata without needing tiles.
   *
   * Returns { nodegroupId, isSingle, targetNodeId } — enough for the JS layer to
   * lazy-load just that nodegroup's tiles before calling getValuesAtPath.
   */
  resolvePath(path: string): any
  /** Resolve a dot-separated path and return a PseudoList. */
  getValuesAtPath(path: string): NapiPseudoList
  /**
   * Get semantic child value for a parent/child relationship.
   * Returns a NapiPseudoList (or null for empty). Singles are wrapped in a
   * single-element list so the JS `wrapRustPseudo` path works uniformly.
   */
  getSemanticChildValue(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId: string | undefined | null, childAlias: string): NapiPseudoList | null
  /** Get all semantic child values for a parent node. */
  getAllSemanticChildValues(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId?: string | undefined | null): any
  /** Find all semantic children of a parent node (returns map of alias → tile IDs). */
  findSemanticChildren(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId?: string | undefined | null): any
  getCachedPseudo(alias?: string | undefined | null): NapiPseudoList | null
  getRootPseudo(): NapiPseudoValue | null
  cachePseudoList(alias: string, list: NapiPseudoList): void
  cachePseudoValue(alias: string, value: NapiPseudoValue): void
  clearPseudoCache(): void
  /** Construct a PseudoValue from node metadata (for TS wrapper). */
  makePseudoValue(alias: string, tileId: string | undefined | null, isPermitted: boolean, isSingle: boolean): any
  /** Serialize to JSON (tile_data mode — raw values). */
  toJson(): any
  /** Serialize to display JSON (resolved labels). */
  toDisplayJson(rdmCache: NapiRdmCache, nodeConfigManager: NapiNodeConfigManager, language?: string | undefined | null): any
  /** Serialize to display JSON without RDM/config (basic labels only). */
  toDisplayJsonSimple(language?: string | undefined | null): any
  release(): void
}
/**
 * NAPI equivalent of WASMResourceModelWrapper.
 *
 * Provides graph schema access (nodes, edges, nodegroups, permissions, pruning)
 * so that the TS ResourceModelWrapper can delegate to either this or the WASM
 * model wrapper via the backend abstraction.
 */
export declare class NapiResourceModelWrapper {
  /**
   * Create a model wrapper from a graph JSON string.
   *
   * The graph is also registered in the core GRAPH_REGISTRY so that
   * NapiResourceInstanceWrapper can look it up by graph_id.
   */
  constructor(graphJson: string, defaultAllow: boolean)
  /** Create from an already-loaded NapiStaticGraph. */
  static fromGraph(graph: NapiStaticGraph, defaultAllow: boolean): NapiResourceModelWrapper
  getGraphId(): string
  get graph(): any
  set graph(graphJson: string)
  buildNodes(): void
  buildNodesForGraph(graphJson: string): void
  /** Get the root node of the graph. */
  getRootNode(): any
  /** Get all nodes as a Map<string, StaticNode>. */
  getNodeObjects(): Record<string, any>
  /** Get all nodes indexed by alias. */
  getNodeObjectsByAlias(): Record<string, any>
  /** Get a single node by alias. */
  getNodeObjectFromAlias(alias: string): any
  /** Get a single node by node ID. */
  getNodeObjectFromId(id: string): any
  /** Get child nodes for a parent node ID. */
  getChildNodes(nodeId: string): Record<string, any>
  /** Get child node aliases (just strings, not full objects). */
  getChildNodeAliases(nodeId: string): Array<string>
  /** Get edges as Map<parent_id, [child_ids]>. */
  getEdges(): Record<string, Array<string>>
  /** Get all nodegroups. */
  getNodegroupObjects(): Record<string, any>
  /** Get nodegroup IDs. */
  getNodegroupIds(): Array<string>
  /** Get nodegroup name (actually the name of the root node for that nodegroup). */
  getNodegroupName(nodegroupId: string): string
  /** Get node ID from alias. */
  getNodeIdFromAlias(alias: string): string
  get nodes(): Record<string, any>
  get nodesByAlias(): Record<string, any>
  get edges(): Record<string, Array<string>>
  get nodegroups(): Record<string, any>
  /** Get permitted nodegroups as boolean map. */
  getPermittedNodegroups(): Record<string, boolean>
  /** Check if a nodegroup is permitted. */
  isNodegroupPermitted(nodegroupId: string): boolean
  /**
   * Set permitted nodegroups. Accepts an object with boolean values or
   * conditional rule objects { path, allowed }.
   */
  setPermittedNodegroups(permissions: any): void
  setDefaultAllowAllNodegroups(defaultAllow: boolean): void
  setGraphNodes(nodesJson: string): void
  setGraphEdges(edgesJson: string): void
  setGraphNodegroups(nodegroupsJson: string): void
  /** Prune graph to only include permitted nodegroups and their dependencies. */
  pruneGraph(keepFunctions?: Array<string> | undefined | null): void
}
export declare class NapiPrebuildExporter {
  constructor()
  /**
   * Export registered graphs to a directory.
   *
   * Classifies graphs as resource_models or branches based on `isresource`,
   * writes as `{"graph": [graph_data]}` JSON files with sorted keys.
   */
  exportGraphs(graphIds: Array<string>, outDir: string): Array<string>
  /** Export all registered graphs to a directory. */
  exportAllGraphs(outDir: string): Array<string>
  /**
   * Build complete export data as JSON (without writing to filesystem).
   *
   * Returns an object with `files` array of `{relativePath, content}` entries.
   */
  buildExportData(graphIds: Array<string> | undefined | null, baseUri: string): any
  /** Get IDs of all registered graphs. */
  getRegisteredGraphIds(): Array<string>
}
export declare class NapiStaticGraph {
  /** Parse a graph from a JSON string (the file content, not a file path). */
  static fromJsonString(jsonStr: string): NapiStaticGraph
  get graphId(): string
  get name(): any
  /** Register this graph in the global registry so NapiResourceInstanceWrapper can use it. */
  register(): void
}
export declare class NapiStaticResourceRegistry {
  constructor()
  /** Insert full resources (with tiles) from a JSON array of StaticResource. */
  mergeFromResourcesJson(resourcesJson: string, storeFull?: boolean | undefined | null): void
  /**
   * Load a business_data file from raw bytes (Buffer), parse entirely in Rust,
   * merge into this registry, and return lightweight refs.
   *
   * Equivalent to the WASM `loadFromBusinessDataBytes` but runs natively —
   * no WASM linear memory limit, and panics produce real stack traces.
   */
  loadFromBusinessDataBytes(bytes: Buffer, storeFull?: boolean | undefined | null, includeCaches?: boolean | undefined | null): Array<any>
  /** Insert full resources from a business_data JSON file string. */
  mergeFromBusinessDataJson(businessDataJson: string, storeFull?: boolean | undefined | null): void
  /** Build an inverted index: visibility value -> [resource IDs]. */
  getValueToResourcesIndex(graph: NapiStaticGraph, nodeIdentifier: string, flattenLocalized?: boolean | undefined | null): Record<string, Array<string>>
  /**
   * Extract values from one node in tiles where another node matches a filter.
   *
   * Both nodes must be in the same nodegroup. Returns raw JSON values from
   * the extract node for each tile where the filter node's display value
   * contains any of the filter values.
   */
  getFilteredTileValues(graph: NapiStaticGraph, filterNode: string, filterValues: Array<string>, extractNode: string, flattenLocalized?: boolean | undefined | null, requiredScope?: string | undefined | null): any
  /** Build a forward index: resource ID -> [node values]. */
  getNodeValuesIndex(graph: NapiStaticGraph, nodeIdentifier: string): any
  get length(): number
  contains(resourceId: string): boolean
  hasFull(resourceId: string): boolean
  /** Get the full resource (with tiles) as a JSON object, or null if only summary stored. */
  getFull(resourceId: string): any | null
  /** Get a summary for a resource (works for both summary and full entries), or null if unknown. */
  getSummary(resourceId: string): any | null
}
