/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Build a StaticGraph from model CSVs (graph.csv, nodes.csv, optional collections.csv).
 *
 * Returns the graph as a JSON string. The `rdm_namespace` is used for
 * deterministic ID generation (typically a UUID or URL).
 */
export declare function buildGraphFromCsvs(graphCsv: string, nodesCsv: string, collectionsCsv: string | undefined | null, rdmNamespace: string): any
/**
 * Build StaticResources from a business data CSV, given a graph JSON string
 * and collections JSON string (as returned by `buildGraphFromCsvs`).
 *
 * Returns the resources wrapped in the `{ business_data: { resources: [...] } }`
 * format expected by PrebuildLoader.
 */
export declare function buildBusinessDataFromCsv(csvData: string, graphJson: string, collectionsJson: string): any
export declare class NapiRdmCache {
  constructor()
  /** Load collections from a SKOS JSON string. */
  loadFromSkosJson(jsonStr: string): void
  /** Load a single collection from JSON. */
  loadCollectionJson(jsonStr: string): void
  get collectionCount(): number
}
export declare class NapiNodeConfigManager {
  constructor()
  /** Build node configs from a graph JSON string. */
  buildFromGraphJson(graphJson: string): void
  /** Build node configs from a NapiStaticGraph. */
  buildFromGraph(graph: NapiStaticGraph): void
}
export declare class NapiPseudoValue {
  get node(): any
  get nodeId(): string | null
  get nodeAlias(): string | null
  get datatype(): string
  get nodegroupId(): string | null
  get isCollector(): boolean
  get independent(): boolean
  get exportable(): boolean
  get isrequired(): boolean
  get issearchable(): boolean
  get ontologyclass(): any
  get hascustomalias(): boolean
  get parentproperty(): string | null
  get description(): any
  get name(): any
  get tileId(): string | null
  get tileData(): any
  get valueLoaded(): boolean
  hasTileData(): boolean
  setTileData(value: any): void
  get childNodeAliases(): any
  getChildNodeId(index: number): string | null
  isIterable(): boolean
  /** Get sortorder from the tile */
  get sortorder(): any
  /** Snapshot all properties in one call (avoids multiple N-API boundary crossings) */
  toSnapshot(): any
  /** Clear tile data */
  clear(): void
}
export declare class NapiPseudoList {
  get nodeAlias(): string
  get totalValues(): number
  get isLoaded(): boolean
  get isSingle(): boolean
  isIterable(): boolean
  getValue(valueIndex: number): NapiPseudoValue | null
  getAllValues(): Array<NapiPseudoValue>
}
export declare class NapiPopulateResult {
  getValueAliases(): Array<string>
  getValue(alias: string): NapiPseudoList | null
  /** Get all values as a JSON map (single boundary crossing). */
  getAllValues(): any
  get allValuesMap(): any
  get allNodegroupsMap(): any
}
export declare class NapiEnsureNodegroupResult {
  getValueAliases(): Array<string>
  getValue(alias: string): NapiPseudoList | null
  getAllValues(): any
  get impliedNodegroups(): Array<string>
  get allNodegroupsMap(): any
}
export declare class NapiValuesFromNodegroupResult {
  getAllValues(): any
  get impliedNodegroups(): Array<string>
}
export declare class NapiResourceInstanceWrapper {
  /** Create a wrapper for a given graph (must be registered). */
  constructor(graphId: string)
  /** Load tiles from a JSON array. */
  loadTiles(tilesJs: any): void
  /** Load tiles directly from a StaticResource JSON. */
  loadTilesFromResource(resourceJs: any): void
  /** Append tiles incrementally (for lazy loading). */
  appendTiles(tilesJs: any): void
  getTileCount(): number
  /**
   * Export all tiles as a JSON string.
   * Returns the wrapper's current tile state (including any mutations from setTileDataForNode).
   * Returned as a string for fast boundary crossing — call JSON.parse() on the JS side.
   */
  exportTilesJson(): string
  tilesLoaded(): boolean
  getAllTileIds(): Array<string>
  getTileIdsByNodegroup(nodegroupId?: string | undefined | null): Array<string>
  getTile(tileId: string): any
  getTileData(tileId: string, nodeId: string): any
  /**
   * Set a single node's data in a tile, mutating in place.
   * Returns true if the tile was found and updated.
   */
  setTileDataForNode(tileId: string, nodeId: string, value: any): boolean
  hasTilesForNodegroup(nodegroupId: string): boolean
  getNodegroupCount(): number
  setLazy(lazy: boolean): void
  isNodegroupLoaded(nodegroupId?: string | undefined | null): boolean
  isNodegroupLoadedOrLoading(nodegroupId?: string | undefined | null): boolean
  tryAcquireNodegroupLock(nodegroupId: string): boolean
  getMissingNodegroupsForChildren(parentNodeId: string): Array<string>
  getResourceId(): string | null
  getName(): any
  getDescriptors(recompute: boolean): any
  /** Populate the pseudo cache for the given nodegroups. */
  populate(lazy: boolean, nodegroupIds: Array<string>, rootNodeAlias: string): NapiPopulateResult
  /** Ensure a single nodegroup is loaded and return structured values. */
  ensureNodegroup(allValuesJs: any, allNodegroupsJs: any, nodegroupId: string, addIfMissing: boolean, nodegroupPermissionsJs: any, doImpliedNodegroups: boolean): NapiEnsureNodegroupResult
  /** Build pseudo values from tiles for a specific nodegroup. */
  valuesFromResourceNodegroup(existingValuesJs: any, nodegroupTileIds: Array<string>, nodegroupId: string): NapiValuesFromNodegroupResult
  /** Resolve a dot-separated path and return a PseudoList. */
  getValuesAtPath(path: string): NapiPseudoList
  /** Get semantic child value for a parent/child relationship. */
  getSemanticChildValue(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId: string | undefined | null, childAlias: string): any
  /** Get all semantic child values for a parent node. */
  getAllSemanticChildValues(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId?: string | undefined | null): any
  /** Find all semantic children of a parent node (returns map of alias → tile IDs). */
  findSemanticChildren(parentTileId: string | undefined | null, parentNodeId: string, parentNodegroupId?: string | undefined | null): any
  getCachedPseudo(alias?: string | undefined | null): NapiPseudoList | null
  getRootPseudo(): NapiPseudoValue | null
  cachePseudoList(alias: string, list: NapiPseudoList): void
  cachePseudoValue(alias: string, value: NapiPseudoValue): void
  clearPseudoCache(): void
  /** Construct a PseudoValue from node metadata (for TS wrapper). */
  makePseudoValue(alias: string, tileId: string | undefined | null, isPermitted: boolean, isSingle: boolean): any
  /** Serialize to JSON (tile_data mode — raw values). */
  toJson(): any
  /** Serialize to display JSON (resolved labels). */
  toDisplayJson(rdmCache: NapiRdmCache, nodeConfigManager: NapiNodeConfigManager, language?: string | undefined | null): any
  /** Serialize to display JSON without RDM/config (basic labels only). */
  toDisplayJsonSimple(language?: string | undefined | null): any
  release(): void
}
/**
 * NAPI equivalent of WASMResourceModelWrapper.
 *
 * Provides graph schema access (nodes, edges, nodegroups, permissions, pruning)
 * so that the TS ResourceModelWrapper can delegate to either this or the WASM
 * model wrapper via the backend abstraction.
 */
export declare class NapiResourceModelWrapper {
  /**
   * Create a model wrapper from a graph JSON string.
   *
   * The graph is also registered in the core GRAPH_REGISTRY so that
   * NapiResourceInstanceWrapper can look it up by graph_id.
   */
  constructor(graphJson: string, defaultAllow: boolean)
  /** Create from an already-loaded NapiStaticGraph. */
  static fromGraph(graph: NapiStaticGraph, defaultAllow: boolean): NapiResourceModelWrapper
  getGraphId(): string
  get graph(): any
  set graph(graphJson: string)
  buildNodes(): void
  buildNodesForGraph(graphJson: string): void
  /** Get the root node of the graph. */
  getRootNode(): any
  /** Get all nodes as a Map<string, StaticNode>. */
  getNodeObjects(): Record<string, any>
  /** Get all nodes indexed by alias. */
  getNodeObjectsByAlias(): Record<string, any>
  /** Get a single node by alias. */
  getNodeObjectFromAlias(alias: string): any
  /** Get a single node by node ID. */
  getNodeObjectFromId(id: string): any
  /** Get child nodes for a parent node ID. */
  getChildNodes(nodeId: string): Record<string, any>
  /** Get child node aliases (just strings, not full objects). */
  getChildNodeAliases(nodeId: string): Array<string>
  /** Get edges as Map<parent_id, [child_ids]>. */
  getEdges(): Record<string, Array<string>>
  /** Get all nodegroups. */
  getNodegroupObjects(): Record<string, any>
  /** Get nodegroup IDs. */
  getNodegroupIds(): Array<string>
  /** Get nodegroup name (actually the name of the root node for that nodegroup). */
  getNodegroupName(nodegroupId: string): string
  /** Get node ID from alias. */
  getNodeIdFromAlias(alias: string): string
  get nodes(): Record<string, any>
  get nodesByAlias(): Record<string, any>
  get edges(): Record<string, Array<string>>
  get nodegroups(): Record<string, any>
  /** Get permitted nodegroups as boolean map. */
  getPermittedNodegroups(): Record<string, boolean>
  /** Check if a nodegroup is permitted. */
  isNodegroupPermitted(nodegroupId: string): boolean
  /**
   * Set permitted nodegroups. Accepts an object with boolean values or
   * conditional rule objects { path, allowed }.
   */
  setPermittedNodegroups(permissions: any): void
  setDefaultAllowAllNodegroups(defaultAllow: boolean): void
  setGraphNodes(nodesJson: string): void
  setGraphEdges(edgesJson: string): void
  setGraphNodegroups(nodegroupsJson: string): void
  /** Prune graph to only include permitted nodegroups and their dependencies. */
  pruneGraph(keepFunctions?: Array<string> | undefined | null): void
}
export declare class NapiPrebuildLoader {
  constructor(path: string)
  /** Load a single graph from a JSON file path (relative to prebuild root or absolute). */
  loadGraph(path: string): NapiStaticGraph
  /** Load all graphs from prebuild/graphs/resource_models/ */
  loadAllGraphs(): Array<NapiStaticGraph>
  /**
   * Load full resources (with tiles) from a single business data file,
   * filtered by graph ID.
   */
  loadFullResourcesFromFile(path: string, graphId: string): any
  /** Find all business data JSON files in the prebuild directory. */
  findBusinessDataFiles(): Array<string>
  /** Get prebuild directory info. */
  getInfo(): any
  /** Count resources for a given graph ID. */
  countResourcesForGraph(graphId: string): number
}
export declare class NapiStaticGraph {
  /** Parse a graph from a JSON string (the file content, not a file path). */
  static fromJsonString(jsonStr: string): NapiStaticGraph
  get graphId(): string
  get name(): any
  /** Register this graph in the global registry so NapiResourceInstanceWrapper can use it. */
  register(): void
}
export declare class NapiStaticResourceRegistry {
  constructor()
  /** Insert full resources (with tiles) from a JSON array of StaticResource. */
  mergeFromResourcesJson(resourcesJson: string, storeFull?: boolean | undefined | null): void
  /**
   * Load a business_data file from raw bytes (Buffer), parse entirely in Rust,
   * merge into this registry, and return lightweight refs.
   *
   * Equivalent to the WASM `loadFromBusinessDataBytes` but runs natively —
   * no WASM linear memory limit, and panics produce real stack traces.
   */
  loadFromBusinessDataBytes(bytes: Buffer, storeFull?: boolean | undefined | null, includeCaches?: boolean | undefined | null): Array<any>
  /** Insert full resources from a business_data JSON file string. */
  mergeFromBusinessDataJson(businessDataJson: string, storeFull?: boolean | undefined | null): void
  /** Build an inverted index: visibility value -> [resource IDs]. */
  getValueToResourcesIndex(graph: NapiStaticGraph, nodeIdentifier: string, flattenLocalized?: boolean | undefined | null): Record<string, Array<string>>
  /**
   * Extract values from one node in tiles where another node matches a filter.
   *
   * Both nodes must be in the same nodegroup. Returns raw JSON values from
   * the extract node for each tile where the filter node's display value
   * contains any of the filter values.
   */
  getFilteredTileValues(graph: NapiStaticGraph, filterNode: string, filterValues: Array<string>, extractNode: string, flattenLocalized?: boolean | undefined | null, requiredScope?: string | undefined | null): any
  /** Build a forward index: resource ID -> [node values]. */
  getNodeValuesIndex(graph: NapiStaticGraph, nodeIdentifier: string): any
  get length(): number
  contains(resourceId: string): boolean
  hasFull(resourceId: string): boolean
  /** Get the full resource (with tiles) as a JSON object, or null if only summary stored. */
  getFull(resourceId: string): any | null
  /** Get a summary for a resource (works for both summary and full entries), or null if unknown. */
  getSummary(resourceId: string): any | null
}
