/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class NapiPrebuildLoader {
  constructor(path: string)
  /** Load a single graph from a JSON file path (relative to prebuild root or absolute). */
  loadGraph(path: string): NapiStaticGraph
  /** Load all graphs from prebuild/graphs/resource_models/ */
  loadAllGraphs(): Array<NapiStaticGraph>
  /**
   * Load full resources (with tiles) from a single business data file,
   * filtered by graph ID.
   */
  loadFullResourcesFromFile(path: string, graphId: string): any
  /** Load all full resources from a single business data file (all graphs). */
  loadAllFullResourcesFromFile(path: string): any
  /** Find all business data JSON files in the prebuild directory. */
  findBusinessDataFiles(): Array<string>
  /** Get prebuild directory info. */
  getInfo(): any
  /** Count resources for a given graph ID. */
  countResourcesForGraph(graphId: string): number
}
export declare class NapiStaticGraph {
  /** Parse a graph from a JSON string (the file content, not a file path). */
  static fromJsonString(jsonStr: string): NapiStaticGraph
  get graphId(): string
  get name(): any
}
export declare class NapiStaticResourceRegistry {
  constructor()
  /** Insert full resources (with tiles) from a JSON array of StaticResource. */
  mergeFromResourcesJson(resourcesJson: string, storeFull?: boolean | undefined | null): void
  /** Insert full resources from a business_data JSON file string. */
  mergeFromBusinessDataJson(businessDataJson: string, storeFull?: boolean | undefined | null): void
  /** Build an inverted index: visibility value -> [resource IDs]. */
  getValueToResourcesIndex(graph: NapiStaticGraph, nodeIdentifier: string, flattenLocalized?: boolean | undefined | null): Record<string, Array<string>>
  /**
   * Extract values from one node in tiles where another node matches a filter.
   *
   * Both nodes must be in the same nodegroup. Returns raw JSON values from
   * the extract node for each tile where the filter node's display value
   * contains any of the filter values.
   */
  getFilteredTileValues(graph: NapiStaticGraph, filterNode: string, filterValues: Array<string>, extractNode: string, flattenLocalized?: boolean | undefined | null, requiredScope?: string | undefined | null): any
  /** Build a forward index: resource ID -> [node values]. */
  getNodeValuesIndex(graph: NapiStaticGraph, nodeIdentifier: string): any
  get length(): number
  contains(resourceId: string): boolean
  hasFull(resourceId: string): boolean
}
