/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * The file-list handler's `TypeHandlerInfo` pointer, as a `BigInt`. Pass to
 * `registerExtensionHandler` from `@alizarin/napi`.
 */
export declare function fileListHandlerPtr(): bigint
