// Auto-registers the file-list handler with @alizarin/napi on import. The native
// binding (index.js) is generated by `napi build` and exposes
// `fileListHandlerPtr()` — a BigInt pointer to the handler's TypeHandlerInfo.
const binding = require('./index.js')
const { registerExtensionHandler } = require('@alizarin/napi')

registerExtensionHandler(binding.fileListHandlerPtr())

module.exports = binding
