// Auto-registers the CLM `reference` handler with @alizarin/napi on import.
// The native binding (index.js) is generated by `napi build` and exposes
// `referenceHandlerPtr()` — a BigInt pointer to the handler's TypeHandlerInfo,
// which we hand to the host's registerExtensionHandler (the NAPI analogue of
// Python's `import alizarin_clm`).
//
//   const alizarin = require('@alizarin/napi');
//   require('@alizarin/clm'); // registers the handler
//
const binding = require('./index.js')
const { registerExtensionHandler } = require('@alizarin/napi')

registerExtensionHandler(binding.referenceHandlerPtr())

module.exports = binding
