name: Check code
on: push
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm i
      - run: npm test
      - run: npx eslint src --max-warnings 46 # RMV
